Following guide in https://github.com/ekapope/WorldWeatherOnline/tree/master/wwo_hist

# Text Scrapping Assignment
Precipitation is a major driver for non-point source pollutants runoff, and the impact of precipitation may vary annually, seasonally, or even monthly. For example, soil is more prone to erosion during planting seasons (March-May) when land cover is minimal. Consequently, a similar precipitation events (intensity and duration) may result in greater soil erosion during planting season as compared to the late-growing season. <br>

Therefore, it is important to understand the precipitation pattern when evaluating the fate and transport of non-point source pollutants. The objectives of this task are: <br>
1) To gather historical precipitation data through an open API <br>
2) Calculate 30-year average annual precipitation depth <br>
3) Calculate annual precipitation depth for the monitoring years (2016-2018) <br>
4) Compare annual precipitation depth to the 30-year average, then determine if it is a dry, normal, or wet year <br>
5) Calculate 30-year average monthly precipitation depth <br>
6) Calculate monthly precipitation depth, then determine if it is a dry, normal, or wet month <br>

In the future development, this data will be paired with nutrient concentration and loading data to identify any possible correlations.

In [76]:
import urllib
import urllib.parse
import json
import pandas as pd
import datetime as dt
import calendar
from datetime import datetime
import pprint

pd.set_option('mode.chained_assignment', None)

In [2]:
def extract_monthly_data(data):
    num_days = len(data)
    # initialize df_month to store return data
    df_month = pd.DataFrame()
    for i in range(num_days):
        # extract this day
        d = data[i]
        # astronomy data is the same for the whole day
        astr_df = pd.DataFrame(d['astronomy'])
        # hourly data; temperature for each hour of the day
        hourly_df = pd.DataFrame(d['hourly'])
        # this wanted_key will be duplicated and use 'ffill' to fill up the NAs
        wanted_keys = ['date', 'maxtempC', 'mintempC', 'totalSnow_cm', 'sunHour', 'uvIndex'] # The keys you want
        subset_d = dict((k, d[k]) for k in wanted_keys if k in d)
        this_df = pd.DataFrame(subset_d,index=[0])        
        df = pd.concat([this_df.reset_index(drop=True), astr_df], axis=1)
        # concat selected astonomy columns with hourly data
        df = pd.concat([df,hourly_df], axis=1)
        df = df.fillna(method='ffill')
        # make date_time columm to proper format
        # fill leading zero for hours to 4 digits (0000-2400 hr)
        df['time'] = df['time'].apply(lambda x: x.zfill(4))
        # keep only first 2 digit (00-24 hr) 
        df['time'] = df['time'].str[:2]
        # convert to pandas datetime
        df['date_time'] = pd.to_datetime(df['date'] + ' ' + df['time'])
        # keep only interested columns
        col_to_keep = ['date_time', 'maxtempC', 'mintempC', 'totalSnow_cm', 'sunHour', 'uvIndex', 
               'moon_illumination', 'moonrise', 'moonset', 'sunrise', 'sunset', 
               'DewPointC',  'FeelsLikeC', 'HeatIndexC', 'WindChillC', 'WindGustKmph',
               'cloudcover', 'humidity', 'precipMM', 'pressure', 'tempC', 'visibility',
               'winddirDegree', 'windspeedKmph']
        df = df[col_to_keep]
        df_month = pd.concat([df_month,df])
    return(df_month)

In [3]:
#function to retrive data by date range and location
#default frequency = 1 hr
#each month costs 1 request (free trial 500 requests/key, as of 30-May-2019)
def retrieve_this_location(api_key,location,start_date,end_date,frequency):
    
    start_time = datetime.now()
    
    # create list of months, convert to month begins (first day of each month)
    list_mon_begin= pd.date_range(start_date,end_date, freq='1M')-pd.offsets.MonthBegin(1)
    # convert to Series and append first day of the last month
    list_mon_begin = pd.concat([pd.Series(list_mon_begin), pd.Series(pd.to_datetime(end_date,infer_datetime_format=True).replace(day=1))], ignore_index=True)
    # change the begin date to start_date
    list_mon_begin[0] = pd.to_datetime(start_date,infer_datetime_format=True)
    
    # create list of months, convert to month ends (last day of each month)
    list_mon_end = pd.date_range(start_date,end_date, freq='1M')-pd.offsets.MonthEnd(0)
    # convert to Series and append the end_date
    list_mon_end = pd.concat([pd.Series(list_mon_end), pd.Series(pd.to_datetime(end_date,infer_datetime_format=True))], ignore_index=True)
    
    # count number of months to be retrieved
    total_months = len(list_mon_begin)

    # initialize df_hist to store return data
    df_hist = pd.DataFrame()
    for m in range(total_months):
        
        start_d =str(list_mon_begin[m])[:10]
        end_d =str(list_mon_end[m])[:10]
        print('Currently retrieving data for '+location+': from '+start_d+' to '+end_d)
        
        url_page = 'http://api.worldweatheronline.com/premium/v1/past-weather.ashx?key='+api_key+'&q='+location+'&format=json&date='+start_d+'&enddate='+end_d+'&tp='+str(frequency)
        json_page = urllib.request.urlopen(url_page)
        json_data = json.loads(json_page.read().decode())
        data= json_data['data']['weather']
       # call function to extract json object
        df_this_month = extract_monthly_data(data)
        df_hist = pd.concat([df_hist,df_this_month])
        
        time_elapsed = datetime.now() - start_time
        print('Time elapsed (hh:mm:ss.ms) {}'.format(time_elapsed))
    return(df_hist)

In [4]:
# retrieving data for dates provided by user

API_key = '3bbd19dc238c4542a08213223192409'
location = '42.2422,-95.0381'
startdate = input('Enter start date as YYYY-MM-DD')
enddate = input('Enter end date as YYYY-MM-DD')
startdate = datetime.strptime(startdate, '%Y-%m-%d')
enddate = datetime.strptime(enddate, '%Y-%m-%d')
weather_data  = retrieve_this_location(API_key, location, startdate, enddate,'default')

Enter start date as YYYY-MM-DD2016-01-01
Enter end date as YYYY-MM-DD2018-12-31
Currently retrieving data for 42.2422,-95.0381: from 2016-01-01 to 2016-01-31
Time elapsed (hh:mm:ss.ms) 0:00:02.363554
Currently retrieving data for 42.2422,-95.0381: from 2016-02-01 to 2016-02-29
Time elapsed (hh:mm:ss.ms) 0:00:03.766221
Currently retrieving data for 42.2422,-95.0381: from 2016-03-01 to 2016-03-31
Time elapsed (hh:mm:ss.ms) 0:00:05.475534
Currently retrieving data for 42.2422,-95.0381: from 2016-04-01 to 2016-04-30
Time elapsed (hh:mm:ss.ms) 0:00:07.121762
Currently retrieving data for 42.2422,-95.0381: from 2016-05-01 to 2016-05-31
Time elapsed (hh:mm:ss.ms) 0:00:09.634654
Currently retrieving data for 42.2422,-95.0381: from 2016-06-01 to 2016-06-30
Time elapsed (hh:mm:ss.ms) 0:00:11.322021
Currently retrieving data for 42.2422,-95.0381: from 2016-07-01 to 2016-07-31
Time elapsed (hh:mm:ss.ms) 0:00:12.826551
Currently retrieving data for 42.2422,-95.0381: from 2016-08-01 to 2016-08-31
Time elapsed (hh:mm:ss.ms) 0:00:14.535724
Currently retrieving data for 42.2422,-95.0381: from 2016-09-01 to 2016-09-30
Time elapsed (hh:mm:ss.ms) 0:00:16.308162
Currently retrieving data for 42.2422,-95.0381: from 2016-10-01 to 2016-10-31
Time elapsed (hh:mm:ss.ms) 0:00:18.182644
Currently retrieving data for 42.2422,-95.0381: from 2016-11-01 to 2016-11-30
Time elapsed (hh:mm:ss.ms) 0:00:19.783329
Currently retrieving data for 42.2422,-95.0381: from 2016-12-01 to 2016-12-31
Time elapsed (hh:mm:ss.ms) 0:00:21.416446
Currently retrieving data for 42.2422,-95.0381: from 2017-01-01 to 2017-01-31
Time elapsed (hh:mm:ss.ms) 0:00:22.890709
Currently retrieving data for 42.2422,-95.0381: from 2017-02-01 to 2017-02-28
Time elapsed (hh:mm:ss.ms) 0:00:24.377822
Currently retrieving data for 42.2422,-95.0381: from 2017-03-01 to 2017-03-31
Time elapsed (hh:mm:ss.ms) 0:00:26.101817
Currently retrieving data for 42.2422,-95.0381: from 2017-04-01 to 2017-04-30
Time elapsed (hh:mm:ss.ms) 0:00:29.404232
Currently retrieving data for 42.2422,-95.0381: from 2017-05-01 to 2017-05-31
Time elapsed (hh:mm:ss.ms) 0:00:30.952247
Currently retrieving data for 42.2422,-95.0381: from 2017-06-01 to 2017-06-30
Time elapsed (hh:mm:ss.ms) 0:00:32.358048
Currently retrieving data for 42.2422,-95.0381: from 2017-07-01 to 2017-07-31
Time elapsed (hh:mm:ss.ms) 0:00:34.774449
Currently retrieving data for 42.2422,-95.0381: from 2017-08-01 to 2017-08-31
Time elapsed (hh:mm:ss.ms) 0:00:36.228003
Currently retrieving data for 42.2422,-95.0381: from 2017-09-01 to 2017-09-30
Time elapsed (hh:mm:ss.ms) 0:00:37.681939
Currently retrieving data for 42.2422,-95.0381: from 2017-10-01 to 2017-10-31
Time elapsed (hh:mm:ss.ms) 0:00:39.147923
Currently retrieving data for 42.2422,-95.0381: from 2017-11-01 to 2017-11-30
Time elapsed (hh:mm:ss.ms) 0:00:40.656303
Currently retrieving data for 42.2422,-95.0381: from 2017-12-01 to 2017-12-31
Time elapsed (hh:mm:ss.ms) 0:00:42.221343
Currently retrieving data for 42.2422,-95.0381: from 2018-01-01 to 2018-01-31
Time elapsed (hh:mm:ss.ms) 0:00:43.697641
Currently retrieving data for 42.2422,-95.0381: from 2018-02-01 to 2018-02-28
Time elapsed (hh:mm:ss.ms) 0:00:45.042075
Currently retrieving data for 42.2422,-95.0381: from 2018-03-01 to 2018-03-31
Time elapsed (hh:mm:ss.ms) 0:00:46.711643
Currently retrieving data for 42.2422,-95.0381: from 2018-04-01 to 2018-04-30
Time elapsed (hh:mm:ss.ms) 0:00:48.632896
Currently retrieving data for 42.2422,-95.0381: from 2018-05-01 to 2018-05-31
Time elapsed (hh:mm:ss.ms) 0:00:50.157178
Currently retrieving data for 42.2422,-95.0381: from 2018-06-01 to 2018-06-30
Time elapsed (hh:mm:ss.ms) 0:00:51.688122
Currently retrieving data for 42.2422,-95.0381: from 2018-07-01 to 2018-07-31
Time elapsed (hh:mm:ss.ms) 0:00:53.685901
Currently retrieving data for 42.2422,-95.0381: from 2018-08-01 to 2018-08-31
Time elapsed (hh:mm:ss.ms) 0:00:55.142711
Currently retrieving data for 42.2422,-95.0381: from 2018-09-01 to 2018-09-30
Time elapsed (hh:mm:ss.ms) 0:00:56.578225
Currently retrieving data for 42.2422,-95.0381: from 2018-10-01 to 2018-10-31
Time elapsed (hh:mm:ss.ms) 0:00:58.097824
Currently retrieving data for 42.2422,-95.0381: from 2018-11-01 to 2018-11-30
Time elapsed (hh:mm:ss.ms) 0:00:59.631169
Currently retrieving data for 42.2422,-95.0381: from 2018-12-01 to 2018-12-31
Time elapsed (hh:mm:ss.ms) 0:01:01.177259
Currently retrieving data for 42.2422,-95.0381: from 2018-12-01 to 2018-12-31
Time elapsed (hh:mm:ss.ms) 0:01:01.950293

In [5]:
weather_data.head()

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,uvIndex,moon_illumination,moonrise,moonset,...,WindChillC,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph
0,2016-01-01 00:00:00,-2,-9,0.0,8.7,1,0,50,12:36 AM,12:53 PM,...,-16,34,98,93,0.0,1030,-8,10,288,22
1,2016-01-01 03:00:00,-2,-9,0.0,8.7,1,0,50,12:36 AM,12:53 PM,...,-16,40,92,94,0.0,1029,-8,10,286,27
2,2016-01-01 06:00:00,-2,-9,0.0,8.7,1,0,50,12:36 AM,12:53 PM,...,-18,51,23,90,0.0,1028,-9,10,272,29
3,2016-01-01 09:00:00,-2,-9,0.0,8.7,1,2,50,12:36 AM,12:53 PM,...,-15,56,8,81,0.0,1026,-6,10,268,30
4,2016-01-01 12:00:00,-2,-9,0.0,8.7,1,2,50,12:36 AM,12:53 PM,...,-9,41,16,79,0.0,1024,-2,10,246,26

In [6]:
ppt =  weather_data [['date_time','precipMM','tempC']]
ppt.head()

            date_time precipMM tempC
0 2016-01-01 00:00:00      0.0    -8
1 2016-01-01 03:00:00      0.0    -8
2 2016-01-01 06:00:00      0.0    -9
3 2016-01-01 09:00:00      0.0    -6
4 2016-01-01 12:00:00      0.0    -2

In [7]:
# separate date and time so that daily average can be calculate using "groupby"
ppt['Date']= ppt['date_time'].dt.date

In [8]:
print(ppt.head())
print(ppt.dtypes)

            date_time precipMM tempC        Date
0 2016-01-01 00:00:00      0.0    -8  2016-01-01
1 2016-01-01 03:00:00      0.0    -8  2016-01-01
2 2016-01-01 06:00:00      0.0    -9  2016-01-01
3 2016-01-01 09:00:00      0.0    -6  2016-01-01
4 2016-01-01 12:00:00      0.0    -2  2016-01-01
date_time    datetime64[ns]
precipMM             object
tempC                object
Date                 object
dtype: object

In [20]:
# converting precip and temperature values from object to string then to interger/float
ppt['Date'] = pd.to_datetime(ppt['Date'])
ppt['precipMM'] = ppt['precipMM'].astype(float)
ppt['tempC'] = ppt['tempC'].astype(str).astype(int)

In [122]:
# calculate daily cumulative precip and average temp
daily_ppt = ppt.groupby('Date').agg({'precipMM':'sum', 'tempC':'mean'})
print(daily_ppt.head())
print(daily_ppt.dtypes)

            precipMM   tempC
Date
2016-01-01       0.0  -5.750
2016-01-02       0.0  -6.000
2016-01-03       0.1  -6.625
2016-01-04       0.1 -10.125
2016-01-05       0.0  -4.875
precipMM    float64
tempC       float64
dtype: object

In [59]:
export_ppt = daily_ppt.to_csv('BHL_weather_data.csv', index=True)

startyear = startdate.year
endyear = enddate.year

years = range(startyear, endyear+1)
start, end = startdate, enddate + dt.timedelta(1)

# first For loop is to calculate number of days in each year of interest
y = startyear #year counter
for year in years:
    year_start = dt.datetime(year, 1, 1)
    year_end = dt.datetime(year+1, 1, 1)
    number_of_days = [(min(end, year_end) - max(start, year_start)).days]
    
    # second For loop to calculate cumulative precipitation in the year
    ### 9/27/19 update: I should first slice the df into annual sets (i.e. 2016 one set, 2017 one set)
    ### Google "python using for loop to calculate cumulative value new column" 
    cum_precip = 0
    for day in number_of_days:
        cum_precip = cum_precip + daily_ppt['precipMM']
        print(cum_precip)
        #print(number_of_days)
        
    y = y + 1
    #print(y, number_of_days)

In [123]:
# convert Date index into column

daily_ppt.reset_index(level=0, inplace=True)
daily_ppt ['year'] = pd.DatetimeIndex(daily_ppt['Date']).year


daily_ppt.head()

        Date  precipMM   tempC  year
0 2016-01-01       0.0  -5.750  2016
1 2016-01-02       0.0  -6.000  2016
2 2016-01-03       0.1  -6.625  2016
3 2016-01-04       0.1 -10.125  2016
4 2016-01-05       0.0  -4.875  2016

In [124]:
# slice the dataset based on year
gbl = globals()

startyear = startdate.year
endyear = enddate.year

years = list(range(startyear, endyear+1))
type(years)

for curr_year in years:
    year_name = str(curr_year)
    gbl['ppt_'+year_name] = daily_ppt[daily_ppt['year'] == curr_year]
    # the dataframe for each year can be called using 'ppt_YYYY'

In [121]:
ppt_2017

          Date  precipMM   tempC  year
366 2017-01-01       0.0  -1.375  2017
367 2017-01-02       0.6  -0.375  2017
368 2017-01-03       0.0  -6.750  2017
369 2017-01-04       0.1 -13.500  2017
370 2017-01-05       0.0 -14.375  2017
371 2017-01-06       0.0 -14.750  2017
372 2017-01-07       0.0 -11.875  2017
373 2017-01-08       0.0 -10.250  2017
374 2017-01-09       0.0  -6.875  2017
375 2017-01-10       2.3  -3.625  2017
376 2017-01-11       0.0  -8.000  2017
377 2017-01-12       0.6 -11.875  2017
378 2017-01-13       0.0 -12.500  2017
379 2017-01-14       0.0  -8.125  2017
380 2017-01-15       0.4  -4.750  2017
381 2017-01-16       7.1  -0.750  2017
382 2017-01-17       0.1  -1.875  2017
383 2017-01-18       0.0   0.000  2017
384 2017-01-19       0.0   1.875  2017
385 2017-01-20       0.1   2.375  2017
386 2017-01-21       1.1   2.625  2017
387 2017-01-22       0.1   0.750  2017
388 2017-01-23       0.0   0.125  2017
389 2017-01-24       0.1  -1.250  2017
390 2017-01-25       0.4  -2.000  2017
391 2017-01-26       0.0  -5.000  2017
392 2017-01-27       0.1  -6.250  2017
393 2017-01-28       0.0  -0.375  2017
394 2017-01-29       0.0  -1.375  2017
395 2017-01-30       0.0   1.500  2017
..         ...       ...     ...   ...
701 2017-12-02       0.0   6.875  2017
702 2017-12-03       0.0   8.875  2017
703 2017-12-04       0.0   9.750  2017
704 2017-12-05       0.0  -2.250  2017
705 2017-12-06       0.0  -3.500  2017
706 2017-12-07       0.0  -8.500  2017
707 2017-12-08       0.0  -3.250  2017
708 2017-12-09       0.0  -4.125  2017
709 2017-12-10       0.0   1.750  2017
710 2017-12-11       0.1   1.625  2017
711 2017-12-12       0.0  -3.875  2017
712 2017-12-13       0.1   3.000  2017
713 2017-12-14       0.0  -1.875  2017
714 2017-12-15       0.0   0.750  2017
715 2017-12-16       0.0   3.375  2017
716 2017-12-17       0.0  -0.875  2017
717 2017-12-18       0.0   2.500  2017
718 2017-12-19       0.0   4.250  2017
719 2017-12-20       0.0  -0.125  2017
720 2017-12-21       0.3  -1.500  2017
721 2017-12-22       0.1  -6.375  2017
722 2017-12-23       0.0  -8.875  2017
723 2017-12-24       0.6  -9.250  2017
724 2017-12-25       0.0 -14.875  2017
725 2017-12-26       0.0 -18.750  2017
726 2017-12-27       0.5 -18.250  2017
727 2017-12-28       0.1 -13.000  2017
728 2017-12-29       0.5 -13.750  2017
729 2017-12-30       0.0 -21.125  2017
730 2017-12-31       0.1 -25.500  2017

[365 rows x 4 columns]